# Generated by Django 3.1.4 on 2020-12-31 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201231_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='comment',
            new_name='Intro',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
